package de.uniluebeck.greennav;

import junit.framework.TestCase;

/**
 * Generated by Nemesis on 13.09.2015.
 */
public class AppContextTest extends TestCase
{

    public void setUp() throws Exception
    {
        super.setUp();

    }

    public void tearDown() throws Exception
    {

    }
}