package de.uniluebeck.greennav;

import junit.framework.TestCase;

/**
 * Generated by Nemesis on 13.09.2015.
 */
public class JSInterfaceTest extends TestCase
{

    public void setUp() throws Exception
    {
        super.setUp();

    }

    public void tearDown() throws Exception
    {

    }

    public void testRegisterGPSCallback() throws Exception
    {

    }

    public void testFireGPSChangeEvent() throws Exception
    {

    }

    public void testCreate() throws Exception
    {

    }

    public void testOnBind() throws Exception
    {

    }
}