package de.uniluebeck.greennav;

import junit.framework.TestCase;

/**
 * Generated by Nemesis on 13.09.2015.
 */
public class NavigatorTest extends TestCase
{

    public void setUp() throws Exception
    {
        super.setUp();

    }

    public void tearDown() throws Exception
    {

    }

    public void testOnCreate() throws Exception
    {

    }

    public void testOnResume() throws Exception
    {

    }

    public void testOnPause() throws Exception
    {

    }

    public void testOnSensorChanged() throws Exception
    {

    }

    public void testCalculateDirection() throws Exception
    {

    }

    public void testOnAccuracyChanged() throws Exception
    {

    }
}