package de.uniluebeck.greennav;

import junit.framework.TestCase;

/**
 * Generated by Nemesis on 13.09.2015.
 */
public class TrackerTest extends TestCase
{

    public void setUp() throws Exception
    {
        super.setUp();

    }

    public void tearDown() throws Exception
    {

    }

    public void testRegisterJSInterface() throws Exception
    {

    }

    public void testStopUsingGPS() throws Exception
    {

    }

    public void testGetLatitude() throws Exception
    {

    }

    public void testGetLongitude() throws Exception
    {

    }

    public void testCanGetLocation() throws Exception
    {

    }

    public void testTrack() throws Exception
    {

    }
}