package de.uniluebeck.greennav;

import junit.framework.TestCase;

/**
 * Generated by Nemesis on 13.09.2015.
 */
public class WelcomeScreenTest extends TestCase
{

    public void testFade() throws Exception
    {

    }
}